#!/usr/bin/env sh

COLORS="true"
HOSTNAME="m1"
FILESYSTEM="ext4"
COMPRESSION="zstd"
COMPRESS="false"
PROGNAME=${0##*/}
CURDIR="$(dirname $(readlink -f "$0"))"
LIBDIR="${CURDIR}/lib"
VERSION=$(date +'%y'.'%m'.'%d')
IMGNAME="alarm-odroid-m1-${VERSION}"
ROOTFS_IMG="${CURDIR}/img"
TMPDIR="${CURDIR}/tmp"
CHROOTDIR="${ROOTFS_IMG}/rootfs"
PKG_CACHE="${CHROOTDIR}/var/cache/pacman/pkg"
NSPAWN="systemd-nspawn -q --resolv-conf=copy-host --timezone=off -D"
PKGDIR="/var/cache/alarm/pkg"
IMGDIR="/var/cache/alarm/img"

mkdir -p ${PKGDIR}/pkg-cache
mkdir -p ${IMGDIR}
mkdir -p ${TMPDIR}

enable_colors() {
    ALL_OFF="\e[1;0m"
    BOLD="\e[1;1m"
    GREEN="${BOLD}\e[1;32m"
    BLUE="${BOLD}\e[1;34m"

    PACMAN_COLORS='--color=always'
    PACCACHE_COLORS=''
    MAKEPKG_COLORS=''
}
info() {
    local mesg=$1; shift
    printf "${BLUE}  ->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@"
}
error() {
    local mesg=$1; shift
    printf "${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@"
}
cleanup() {
    umount $PKG_CACHE
    exit ${1:-0}
}
abort() {
    error 'Aborting...'
    cleanup 255
}
prune_cache(){
    info "Pruning and unmounting package cache..."
    $NSPAWN $CHROOTDIR paccache -r $PACCACHE_COLORS
    umount $PKG_CACHE
}
msg() {
    local mesg=$1; shift
    printf "\n${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@"
}
get_timer(){
    echo $(date +%s)
}
elapsed_time(){
    echo $(echo $1 $(get_timer) | awk '{ printf "%0.2f",($2-$1)/60 }')
}
show_elapsed_time(){
    msg "Time elapsed: %s minute(s)" "$(elapsed_time $1)"
}
check_deps () {
	pacman -Qii qemu-user-static-binfmt >/dev/null 2>&1 || (error 'qemu-user-static-binfmt is not installed' && exit 1)
}
check_root () {
    if [ "$EUID" -ne 0 ]; then
        echo "This utility requires root permissions to run"
        exit
    fi
}
check_running() {
    for pid in $(pidof -x $PROGNAME); do
        if [ $pid != $$ ]; then
            echo "Process already running as PID $pid"
            exit 1
        fi
    done
}
create_rootfs_img() {
	msg "Creating rootfs image..."

	if [ -d "$ROOTFS_IMG/rootfs" ]; then
        info "Removing old rootfs..."
        rm -rf $ROOTFS_IMG/rootfs
    fi
	if [ ! -f "$TMPDIR/ArchLinuxARM-aarch64-latest.tar.gz" ]; then
        info "Downloading alarm..."
        curl -L "http://mirror.yandex.ru/archlinux-arm/os/ArchLinuxARM-aarch64-latest.tar.gz" -o "$TMPDIR/ArchLinuxARM-aarch64-latest.tar.gz"
        if [ $? -ne 0 ]; then
            echo "Downloading alarm failed"
            exit 1
        fi
    fi
    info "Extracting rootfs..."
	mkdir -p $ROOTFS_IMG/rootfs
    bsdtar -xpf $CURDIR/../ArchLinuxARM-aarch64-latest.tar.gz -C $ROOTFS_IMG/rootfs

    info "Setting up keyrings..."
    $NSPAWN $ROOTFS_IMG/rootfs pacman-key --init >/dev/null || abort
    $NSPAWN $ROOTFS_IMG/rootfs pacman-key --populate archlinuxarm >/dev/null || abort

    echo "Server = https://mirror.yandex.ru/archlinux-arm/\$arch/\$repo" > $ROOTFS_IMG/rootfs/etc/pacman.d/mirrorlist

    msg "Installing packages..."
    mount --bind $PKGDIR/pkg-cache $PKG_CACHE

    cp $LIBDIR/linux-aarch64.preset $ROOTFS_IMG/rootfs/etc/mkinitcpio.d/linux-aarch64.preset
    cp $LIBDIR/mkinitcpio.conf $ROOTFS_IMG/rootfs/etc/mkinitcpio.conf
    cp $LIBDIR/pacman.conf $ROOTFS_IMG/rootfs/etc/pacman.conf
    cp $LIBDIR/journald.conf $ROOTFS_IMG/rootfs/etc/systemd/journald.conf
    $NSPAWN $ROOTFS_IMG/rootfs \
                    pacman -Syyu base systemd systemd-libs \
                                 sudo openssh micro dhcpcd man-pages man-db usbutils zram-generator irqbalance exfatprogs \
                                 pacman-contrib fish \
                                 linux-aarch64 \
                                 --noconfirm --needed --noprogressbar $PACMAN_COLORS || abort

    info "Enabling services..."
    local SERVICE
    while read SERVICE; do
        if [ -e $ROOTFS_IMG/rootfs/usr/lib/systemd/system/$SERVICE ]; then
            echo "Enabling service $SERVICE..."
            $NSPAWN $ROOTFS_IMG/rootfs systemctl enable $SERVICE >/dev/null 2>&1 || abort
        else
            echo "Service $SERVICE not found in rootfs, skipping"
        fi
    done < "$CURDIR/services_list"

	info "Setting up system settings..."
    $NSPAWN $ROOTFS_IMG/rootfs update-ca-trust || abort
    echo "$HOSTNAME" > $ROOTFS_IMG/rootfs/etc/hostname
    echo 'LANG=en_US.UTF-8' > $ROOTFS_IMG/rootfs/etc/locale.conf
    echo 'KEYMAP=us' > $ROOTFS_IMG/rootfs/etc/vconsole.conf
    echo 'en_US.UTF-8 UTF-8
en_GB.UTF-8 UTF-8
ru_RU.UTF-8 UTF-8' > $ROOTFS_IMG/rootfs/etc/locale.gen

    info 'locale-gen...'
    $NSPAWN $ROOTFS_IMG/rootfs locale-gen
    info 'timezone...'
    $NSPAWN $ROOTFS_IMG/rootfs ln -s /usr/share/zoneinfo/Europe/Samara /etc/localtime
    info 'root password...'
    $NSPAWN $ROOTFS_IMG/rootfs printf "root:$CFG_ROOT_PASSWORD" | chpasswd -e
    info 'add user...'
    $NSPAWN $ROOTFS_IMG/rootfs useradd -m -g users -G audio,video,power,storage,wheel,scanner,network,users -p "$CFG_USER_PASSWORD" -s /bin/fish $CFG_USERNAME

    $NSPAWN $ROOTFS_IMG/rootfs mkinitcpio -P

    $NSPAWN $ROOTFS_IMG/rootfs sudo -u $CFG_USERNAME mkdir -p /home/${CFG_USERNAME}/.ssh
    $NSPAWN $ROOTFS_IMG/rootfs sudo -u $CFG_USERNAME mkdir -p /home/${CFG_USERNAME}/downloads
    $NSPAWN $ROOTFS_IMG/rootfs sudo -u $CFG_USERNAME sh -c "printf 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKPBlmW9r5Y8Zj8cTxECLO9HEY+USByhVDxdPxq++oy2 id_ed25519
' > /home/${CFG_USERNAME}/.ssh/authorized_keys"

	echo "[zram0]" > $ROOTFS_IMG/rootfs/etc/systemd/zram-generator.conf
    echo "%wheel ALL=(ALL) ALL" > $ROOTFS_IMG/rootfs/etc/sudoers.d/wheel

    cp $LIBDIR/post-scriptum $ROOTFS_IMG/rootfs/home/${CFG_USERNAME}/
    cp $LIBDIR/slp.sh $ROOTFS_IMG/rootfs/home/${CFG_USERNAME}/
    cp $LIBDIR/start-ace.sh $ROOTFS_IMG/rootfs/home/${CFG_USERNAME}/
    $NSPAWN $ROOTFS_IMG/rootfs chown "${CFG_USERNAME}:users" /home/${CFG_USERNAME}/post-scriptum /home/${CFG_USERNAME}/slp.sh /home/${CFG_USERNAME}/start-ace.sh

    info "Removing unwanted files from rootfs..."
    prune_cache
    rm -f $ROOTFS_IMG/rootfs/usr/bin/qemu-aarch64-static
    rm -f $ROOTFS_IMG/rootfs/var/log/* > /dev/null 2>&1
    rm -rf $ROOTFS_IMG/rootfs/var/log/journal/*
    rm -f $ROOTFS_IMG/rootfs/etc/*.pacnew
    rm -f $ROOTFS_IMG/rootfs/usr/lib/systemd/system/systemd-firstboot.service
    rm -f $ROOTFS_IMG/rootfs/etc/machine-id
    rm -rf $ROOTFS_IMG/rootfs/etc/pacman.d/gnupg
    rm -rf $ROOTFS_IMG/rootfs/boot/initramfs-linux-fallback.img

    msg "Creating rootfs image completed successfully"
}
create_img() {
	msg "Creating image..."
	info "Creating $FILESYSTEM partitions..."

	SIZE=$(du -s --block-size=MB $CHROOTDIR | awk '{ print $1 }' | sed -e 's/MB//g')
	info "Total size of packages $SIZE MB"
    EXTRA_SIZE=600
    REAL_SIZE=`echo "$(($SIZE+$EXTRA_SIZE))"`

	# Make blank .img to be used
    dd if=/dev/zero of=$IMGDIR/$IMGNAME.img bs=1M count=$REAL_SIZE > /dev/null 2>&1
	# Load the loop kernel module
    modprobe loop > /dev/null 2>&1
    # Set up the loop device
    LDEV=`losetup -f`
    DEV=`echo $LDEV | cut -d "/" -f 3`
    # Mount the image to the loop device
    losetup -P $LDEV $IMGDIR/$IMGNAME.img > /dev/null 2>&1
	# Clear the first 32 MB
    dd if=/dev/zero of=${LDEV} bs=1M count=32 conv=fsync,notrunc > /dev/null 2>&1

	# Create the boot and root partitions
    parted -s $LDEV mklabel gpt >/dev/null 2>&1
    parted -s $LDEV mkpart primary fat32 32M 512M >/dev/null 2>&1
    START=`cat /sys/block/$DEV/${DEV}p1/start`
    SIZE=`cat /sys/block/$DEV/${DEV}p1/size`
    END_SECTOR=$(expr $START + $SIZE)
    parted -s $LDEV mkpart primary ext4 "${END_SECTOR}s" 100% > /dev/null 2>&1
    partprobe $LDEV > /dev/null 2>&1
    mkfs.vfat "${LDEV}p1" -n BOOT_ARCH > /dev/null 2>&1
    mkfs.ext4 -O ^metadata_csum,^64bit "${LDEV}p2" -L ROOT_ARCH > /dev/null 2>&1

    # Copy the rootfs contents over to the filesystem
    info "Copying files to image..."
    mkdir -p $TMPDIR/root
    mkdir -p $TMPDIR/boot
    mount ${LDEV}p1 $TMPDIR/boot
    mount ${LDEV}p2 $TMPDIR/root
    cp -a $ROOTFS_IMG/rootfs/* $TMPDIR/root

    mv $TMPDIR/root/boot/* $TMPDIR/boot
	# Write the boot loader images
    dd if=$TMPDIR/boot/idbloader.img of=${LDEV} seek=64 conv=notrunc,fsync > /dev/null 2>&1
    dd if=$TMPDIR/boot/u-boot.itb of=${LDEV} seek=16384 conv=notrunc,fsync > /dev/null 2>&1

    mkimage -T script -d $LIBDIR/boot_arch_kernel.txt $TMPDIR/boot/boot.scr
    # Fetch the PARTUUIDs
    BOOT_PART=$(lsblk -p -o NAME,PARTUUID | grep "${LDEV}p1" | awk '{ print $2 }')
    ROOT_PART=$(lsblk -p -o NAME,PARTUUID | grep "${LDEV}p2" | awk '{ print $2 }')
    ROOT_UUID=$(blkid | grep "${LDEV}p2" | awk '{print $3}' | grep -oP "[^/]=\K.*" | sed 's/\"//g')
	echo "Boot PARTUUID is $BOOT_PART..."
    echo "Root PARTUUID is $ROOT_PART..."
	echo "Root UUID is $ROOT_UUID..."

	# Adjust the fstab to use the boot PARTUUID
	echo "PARTUUID=$BOOT_PART   /boot   vfat     defaults    0   2" >> $TMPDIR/root/etc/fstab
    echo "PARTUUID=$ROOT_PART   /   $FILESYSTEM     defaults,noatime    0   1" >> $TMPDIR/root/etc/fstab
    echo "UUID=b7f4d396-ab1e-4f29-bcaf-a07303fbf568     /home/azat/downloads    xfs     defaults,user,noatime,noauto    0   3" >> $TMPDIR/root/etc/fstab

    # Clean up
    info "Cleaning up image..."
    umount $TMPDIR/root
    umount $TMPDIR/boot

    losetup -d $LDEV >/dev/null 2>&1
    rm -rf $TMPDIR/boot/efi
    rm -rf $TMPDIR/boot
    rm -rf $TMPDIR/root
    if [ $? -ne 0 ]; then
        echo "Cleaning up image failed, aborting"
        exit 1
    fi
    partprobe $LDEV > /dev/null 2>&1
    chmod 0666 $IMGDIR/$IMGNAME.img
    info "Image $IMGDIR/$IMGNAME.img"
}
compress() {
	info "Compressing $IMGNAME.img with $COMPRESSION..."
    # Compress the image
    cd $IMGDIR
    case "$COMPRESSION" in
        xz)
            if [ -f $IMGDIR/$IMGNAME.img.xz ]; then
                info "Removing existing compressed image file $IMGNAME.img.xz..."
                rm -rf $IMGDIR/$IMGNAME.img.xz
            fi
            xz -zv --threads=0 $IMGNAME.img
            chmod 0666 $IMGDIR/$IMGNAME.img.xz
            ;;
        zstd)
            if [ -f $IMGDIR/$IMGNAME.img.zst ]; then
                info "Removing existing compressed image file $IMGNAME.img.zst..."
                rm -rf $IMGDIR/$IMGNAME.img.zst
            fi
            zstd -z -10 -T0 --rm $IMGNAME.img
            chmod 0666 $IMGDIR/$IMGNAME.img.zst
            ;;
    esac

	mount | grep "$ROOTFS_IMG/rootfs/var/cache/pacman/pkg"
    STATUS=$?
    [ $STATUS -eq 0 ] && umount $ROOTFS_IMG/rootfs_$ARCH/var/cache/pacman/pkg
	info "Removing rootfs..."
	rm -rf $CHROOTDIR
}
# ********************************************************************
# ********************************************************************
# ********************************************************************

. ./.env
if [ -z "$CFG_USERNAME" ]; then
    error "CFG_USERNAME not set"
fi
if [ -z "$CFG_USER_PASSWORD" ]; then
    error "CFG_USER_PASSWORD not set"
fi
if [ -z "$CFG_ROOT_PASSWORD" ]; then
    error "CFG_ROOT_PASSWORD not set"
fi

[ "$COLORS" = "true" ] && enable_colors
check_deps
check_root
check_running
timer_start=$(get_timer)

create_rootfs_img 2>&1

create_img 2>&1

if [ "$COMPRESS" = "true" ]; then
	compress 2>&1
fi

show_elapsed_time "${timer_start}" 2>&1
