#!/usr/bin/env sh

enable_colors() {
    ALL_OFF="\e[1;0m"
    BOLD="\e[1;1m"
    GREEN="${BOLD}\e[1;32m"
    BLUE="${BOLD}\e[1;34m"
}
info() {
    local mesg=$1; shift
    printf "${BLUE}  ->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@"
}
error() {
    local mesg=$1; shift
    printf "${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@"
}
check_root () {
    if [ "$EUID" -ne 0 ]; then
        error "This utility requires root permissions to run"
        exit
    fi
}
enable_colors

resize() {
    PART_DEV=`findmnt / -o source -n | cut -f1 -d"["`
    PART_NAME=`echo $PART_DEV | cut -f3 -d"/"`
    DEV_NAME=`echo /sys/block/*/${PART_NAME} | cut -f4 -d"/"`
    DEV="/dev/${DEV_NAME}"
    PART_NUM=`cat /sys/block/${DEV_NAME}/${PART_NAME}/partition`
    echo ", +" | sudo sfdisk --no-reread -N $PART_NUM $DEV

    sudo partx -u $DEV
    sudo resize2fs $PART_DEV
    sudo timedatectl set-ntp on
}
pacman_init() {
    sudo rm -rf /etc/pacman.d/gnupg
    sudo pacman-key --init
    sudo pacman-key --populate archlinuxarm
}
yay() {
    rm -rf /tmp/yay
    git clone --depth=1 https://aur.archlinux.org/yay-bin.git /tmp/yay
    sh -c 'cd /tmp/yay && makepkg -ris --noconfirm'
}

resize
sleep 1
pacman_init

sudo hwclock --systohc --utc

sudo userdel -f -r alarm

sudo pacman -S --needed --noconfirm smartmontools base-devel git tailscale htop mc yt-dlp ffmpeg jack2

yay

rm post-scriptum
